{
 "title": "AMQ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ns", "query": "amq63" },
   { "name": "jobName", "query": "amq-brokers" }
  ]
 },
 "panels": [
  { "title": "AMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Brokers",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Broker Restarts (incr 30m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{container=\"broker-amq\",namespace=\"$ns\"}[30m])"
    }
   ]
  },
  {
   "title": "Consumer Count",
   "type": "singlestat",
   "gridPos": { "h": 4.5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(activemq_queue_consumer_count{job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_queue_size{job=\"$jobName\"}"
    }
   ]
  },
  {
   "title": "Daily Message Count (24h)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(activemq_queue_enqueue_count{job=\"$jobName\"}[24h])"
    }
   ]
  },
  {
   "title": "Producer Count",
   "type": "singlestat",
   "gridPos": { "h": 4.5, "w": 6, "x": 6, "y": 5.5 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "AMQ (De|En)Q Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Enqueue Rate (5m)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(activemq_queue_enqueue_count{job=\"$jobName\"}[5m])"
      }
     ]
    },
    {
     "title": "Dequeue Rate (5m)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate (activemq_queue_dequeue_count{job=\"$jobName\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "AMQ JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "AMQ Broker Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "MiB" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{job=\"$jobName\"}/(1000*1000)) by (area)"
      }
     ]
    },
    {
     "title": "AMQ JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "MiB" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$jobName\"}"
      }
     ]
    }
   ]
  }
 ]
}