rules:
  - pattern: 'org.apache.activemq<type=Broker,brokerName=\"(.*)\",destinationType="Queue",destinationName=\"(.*)\"><>QueueSize'
    name: QueueSize
    help: Queue Size
    type: GAUGE
    labels:
      name: $1