rules:
  - pattern: 'org.apache.activemq<type=(\w+), brokerName=(\w+), destinationType=(\w+), destinationName=(\w+)><>QueueSize'
    name: queue_size
    help: Queue Size
    type: GAUGE
    labels:
      queue: $4